import { phaseOf } from "./types.js";
import type { StepResult } from "./types.js";

export function renderReport(feature: string, results: StepResult[], generatedAt = "N/A"): string {
  // Only `test` steps are scored; setup/teardown are machinery for preparing and cleaning data.
  const tests = results.filter((r) => phaseOf(r) === "test");
  const pass = tests.filter((r) => r.passed).length;
  const skipped = tests.filter((r) => r.skipped).length;
  const failedSetup = results.filter((r) => phaseOf(r) === "setup" && !r.passed && !r.skipped);

  const lines: string[] = [];
  lines.push(`# E2E Report: ${feature}`, "", `Generated at: ${generatedAt}`, "");
  lines.push(
    `**Result: ${pass}/${tests.length} passed**` + (skipped ? ` · ${skipped} skipped` : ""),
    "",
  );

  if (failedSetup.length) {
    const names = failedSetup.map((r) => r.case ?? `step ${r.index}`).join(", ");
    lines.push(
      `> ⚠️ Setup thất bại (${names}) — các case phía sau **chưa được kiểm**, không phải feature sai.`,
      "",
    );
  }

  lines.push("| Case | Phase | Risk | Target | Scenario | Result | Detail |", "|---|---|---|---|---|---|---|");
  for (const r of results) {
    const mark = r.skipped ? "⏭️ SKIP" : r.passed ? "✅ PASS" : "❌ FAIL";
    lines.push(
      `| ${r.case ?? r.index} | ${phaseOf(r)} | ${r.risk ?? "—"} | ${r.target} | ${escape(r.action)} | ${mark} | ${escape(r.detail)} |`,
    );
  }

  const withErrors = results.filter((r) => r.consoleErrors?.length);
  if (withErrors.length) {
    lines.push("", "## Console errors", "");
    for (const r of withErrors) {
      lines.push(`### Step ${r.index} (${r.target})`, "```", ...(r.consoleErrors ?? []), "```", "");
    }
  }

  lines.push("", "## Analysis", "", "> (Claude fills in root-cause analysis and points to file:line here.)", "");
  return lines.join("\n");
}

function escape(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/**
 * Machine-readable export for Google Sheets / Jira / TestRail.
 *
 * Generated by the engine rather than written by hand: it is a mechanical projection of the run,
 * so producing it here keeps it deterministic, identically formatted every time, and free.
 * `Type` (feature / spec / flaky) is deliberately left blank — that is a judgement made while
 * analysing the failures, not something the runner can infer.
 */
export function renderCsv(results: StepResult[]): string {
  const header = ["TC ID", "Phase", "Target", "Risk", "Status", "Scenario", "Detail", "Type"];
  const rows = results.map((r) => [
    r.case ?? String(r.index),
    phaseOf(r),
    r.target,
    r.risk ?? "",
    r.skipped ? "SKIPPED" : r.passed ? "PASSED" : "FAILED",
    r.action,
    r.detail,
    "",
  ]);
  return [header, ...rows].map((cols) => cols.map(csvCell).join(",")).join("\n") + "\n";
}

/** Quote a CSV field only when needed, doubling any embedded quote (RFC 4180). */
function csvCell(value: string): string {
  return /[",\n\r]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}
